module.exports = [
  { word: 'Pizza', category: 'food', difficulty: 'easy' },
  { word: 'Burger', category: 'food', difficulty: 'easy' },
  { word: 'Apple', category: 'food', difficulty: 'easy' },
  { word: 'Sushi', category: 'food', difficulty: 'medium' },
  { word: 'Croissant', category: 'food', difficulty: 'medium' },
  { word: 'Guacamole', category: 'food', difficulty: 'medium' },
  { word: 'Tiramisu', category: 'food', difficulty: 'hard' },
  { word: 'Bruschetta', category: 'food', difficulty: 'hard' },
  { word: 'Ratatouille', category: 'food', difficulty: 'hard' },

  { word: 'Tom Hanks', category: 'actors', difficulty: 'easy' },
  { word: 'Will Smith', category: 'actors', difficulty: 'easy' },
  { word: 'Emma Stone', category: 'actors', difficulty: 'medium' },
  { word: 'Leonardo DiCaprio', category: 'actors', difficulty: 'medium' },
  { word: 'Denzel Washington', category: 'actors', difficulty: 'hard' },
  { word: 'Meryl Streep', category: 'actors', difficulty: 'hard' },

  { word: 'Lionel Messi', category: 'soccer_players', difficulty: 'easy' },
  { word: 'Cristiano Ronaldo', category: 'soccer_players', difficulty: 'easy' },
  { word: 'Neymar', category: 'soccer_players', difficulty: 'medium' },
  { word: 'Kylian Mbappe', category: 'soccer_players', difficulty: 'medium' },
  { word: 'Luka Modric', category: 'soccer_players', difficulty: 'hard' },
  { word: 'Robert Lewandowski', category: 'soccer_players', difficulty: 'hard' },

  { word: 'Elephant', category: 'animals', difficulty: 'easy' },
  { word: 'Tiger', category: 'animals', difficulty: 'easy' },
  { word: 'Penguin', category: 'animals', difficulty: 'medium' },
  { word: 'Kangaroo', category: 'animals', difficulty: 'medium' },
  { word: 'Platypus', category: 'animals', difficulty: 'hard' },
  { word: 'Chameleon', category: 'animals', difficulty: 'hard' },

  { word: 'Laptop', category: 'objects', difficulty: 'easy' },
  { word: 'Backpack', category: 'objects', difficulty: 'easy' },
  { word: 'Microscope', category: 'objects', difficulty: 'medium' },
  { word: 'Telescope', category: 'objects', difficulty: 'medium' },
  { word: 'Boomerang', category: 'objects', difficulty: 'hard' },
  { word: 'Typewriter', category: 'objects', difficulty: 'hard' },

  { word: 'Running', category: 'actions', difficulty: 'easy' },
  { word: 'Dancing', category: 'actions', difficulty: 'easy' },
  { word: 'Whistling', category: 'actions', difficulty: 'medium' },
  { word: 'Juggling', category: 'actions', difficulty: 'medium' },
  { word: 'Meditating', category: 'actions', difficulty: 'hard' },
  { word: 'Negotiating', category: 'actions', difficulty: 'hard' },

  { word: 'Titanic', category: 'movies', difficulty: 'easy' },
  { word: 'Avatar', category: 'movies', difficulty: 'easy' },
  { word: 'Inception', category: 'movies', difficulty: 'medium' },
  { word: 'Gladiator', category: 'movies', difficulty: 'medium' },
  { word: 'Interstellar', category: 'movies', difficulty: 'hard' },
  { word: 'Casablanca', category: 'movies', difficulty: 'hard' },

  { word: 'Paris', category: 'places', difficulty: 'easy' },
  { word: 'Beach', category: 'places', difficulty: 'easy' },
  { word: 'Airport', category: 'places', difficulty: 'medium' },
  { word: 'Museum', category: 'places', difficulty: 'medium' },
  { word: 'Skyscraper', category: 'places', difficulty: 'hard' },
  { word: 'Amphitheater', category: 'places', difficulty: 'hard' },

  { word: 'Brazil', category: 'countries', difficulty: 'easy' },
  { word: 'Japan', category: 'countries', difficulty: 'easy' },
  { word: 'Argentina', category: 'countries', difficulty: 'medium' },
  { word: 'Portugal', category: 'countries', difficulty: 'medium' },
  { word: 'Liechtenstein', category: 'countries', difficulty: 'hard' },
  { word: 'Kazakhstan', category: 'countries', difficulty: 'hard' }
];
